### ISSUE TITLE
json unmarshal errors

### ISSUE THREAD

**Issue by captn3m0** [Hsn723/ct-monitor#2]
```2021/02/02 12:54:20 ct-monitor version 0.1.1
2021/02/02 12:54:20 using config file:/etc/ct-monitor/config.toml
2021/02/02 12:54:20 using position file:/var/log/ct-monitor/positions.toml
2021/02/02 12:54:21 json: cannot unmarshal object into Go value of type []api.Issuance
2021/02/02 12:54:21 json: cannot unmarshal object into Go value of type []api.Issuance
2021/02/02 12:54:21 json: cannot unmarshal object into Go value of type []api.Issuance
2021/02/02 12:54:21 json: cannot unmarshal object into Go value of type []api.Issuance
```

The container dies after this.

**Comment by Hsn723** [comment]
Do you have a sample repro config.toml? It's hard to tell where the issue is with this output alone.

**Comment by captn3m0** [comment]
```
domains = ["captnemo.in"]
[alert_config]
  from = "ct@captnemo.in"
  recipient = "tech_cert_issuance-aaaadd3wxkjxcxtzldfsdwnzv4@razorpay.slack.com"
  mailer_config = "smtp"

[smtp]
password = "<password>"
server = "smtp.migadu.com"
port = 465

[position_config]
    filename = "/var/log/ct-monitor/positions.toml"
```

Running in docker using `quay.io/hsn723/ct-monitor:latest` with the configuration file mounted to `/etc/ct-monitor/config.toml`. Passing no flags on the command line.

**Comment by captn3m0** [comment]
```toml
domains = ["captnemo.in"]
[alert_config]
  from = "ct@captnemo.in"
  recipient = "<email>"
  mailer_config = "smtp"

[smtp]
password = "<pass>"
server = "smtp.migadu.com"
port = 465

[position_config]
    filename = "/var/log/ct-monitor/positions.toml"
```
Running `quay.io/hsn723/ct-monitor:latest` with no other flags and the configuration mounted to `/etc/ct-monitor/config.toml`.

**Comment by captn3m0** [comment]
I think its hitting the API rate limits, but would be nice to have a confirmation or error message printed

**Comment by Hsn723** [comment]
Thank you for the clarification. It indeed definitely looks like a rate limit issue. The documentation didn't include clear specifications, but it looks like they return an object matching the error object in their v3 REST API with a status code of 429. I'll add some checks for this case.

**Comment by captn3m0** [comment]
Thanks a lot for the quick fix. 💯
